"""Pydantic request/response schemas for the API."""

from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import datetime


class EventLog(BaseModel):
    """Single security event log entry."""
    timestamp: str
    event_type: str
    event_code: int = 0
    user_name: str = "unknown"
    source_ip: str = "0.0.0.0"
    dest_ip: str = "0.0.0.0"
    auth_type: str = "unknown"
    device_type: str = "unknown"
    hour_of_day: int = 12
    day_of_week: int = 0
    is_weekend: bool = False
    session_duration_sec: int = 0
    bytes_transferred: int = 0
    failed_attempts_last_1h: int = 0
    unique_dest_ips_last_1h: int = 0
    login_frequency_last_1h: int = 0
    user_role: str = "user"
    asset_type: str = "unknown"
    geo_city: str = "Unknown"
    geo_country: str = "XX"


class EventBatch(BaseModel):
    """Batch of events for bulk analysis."""
    events: List[EventLog] = Field(..., min_length=1, max_length=10000)


class RiskAssessment(BaseModel):
    """Risk assessment result."""
    score: float
    level: str
    anomaly_probability: float
    attack_type: str
    tactic: str
    context_bonus: float
    impact_weight: float
    confidence: float
    risk_factors: List[str]
    recommendations: List[str]
    timestamp: str


class AnalyzeResponse(BaseModel):
    """Response from single event analysis."""
    event_id: str = ""
    risk: RiskAssessment
    anomaly_scores: Dict[str, float]
    mitre_technique_ids: List[str]
    model_version: str = "2.0.0"


class BatchAnalyzeResponse(BaseModel):
    """Response from batch event analysis."""
    total_events: int
    high_risk_count: int
    medium_risk_count: int
    low_risk_count: int
    info_count: int
    results: List[AnalyzeResponse]
    aggregate: Dict[str, Any]


class ModelStatus(BaseModel):
    """Status of loaded ML models."""
    isolation_forest: bool = False
    deep_isolation_forest: bool = False
    autoencoder_vae: bool = False
    sequence_transformer: bool = False
    xgboost_attack_classifier: bool = False
    xgboost_tactic_classifier: bool = False
    risk_scorer: bool = True
    total_events_processed: int = 0


class Alert(BaseModel):
    """Security alert generated by the system."""
    id: str
    timestamp: str
    event_type: str
    user_name: str
    source_ip: str
    risk_score: float
    risk_level: str
    attack_type: str
    tactic: str
    mitre_technique_ids: List[str]
    risk_factors: List[str]
    recommendations: List[str]
    acknowledged: bool = False


class DashboardSummary(BaseModel):
    """Dashboard summary statistics."""
    total_events_analyzed: int
    active_alerts: int
    critical_alerts: int
    high_alerts: int
    medium_alerts: int
    avg_risk_score: float
    top_attack_types: List[Dict[str, Any]]
    risk_over_time: List[Dict[str, Any]]
    entity_risk: List[Dict[str, Any]]
    mitre_coverage: Dict[str, float]
    model_status: ModelStatus


class TrainRequest(BaseModel):
    """Request to train/retrain models."""
    epochs: int = 50
    learning_rate: float = 0.001
    batch_size: int = 256
    force_retrain: bool = False


class TrainResponse(BaseModel):
    """Response from model training."""
    status: str
    models_trained: List[str]
    training_time_seconds: float
    metrics: Dict[str, Any]
